// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/documentation": {
    params: {};
  };
  "/theme": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/documentation" | "/theme";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/documentation.tsx": {
    id: "routes/documentation";
    page: "/documentation";
  };
  "routes/theme.tsx": {
    id: "routes/theme";
    page: "/theme";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/documentation": typeof import("./app/routes/documentation.tsx");
  "routes/theme": typeof import("./app/routes/theme.tsx");
};